# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e-94Y-Fv_QArUqnrxyfOEyKqBoq-LQp
"""

# * * * *
# * * * *
# * * * *
# * * * *

import time
for row in range(4):
  for col in range(4):
    time.sleep(1)
    print("* ", end = " ")
  print()

# 11 12 13 14
# 21 22 23 24
# 31 32 33 34


for row in range(1, 4):
  for col in range(1, 5):
    print(row, col, end = " ")
  print()

# 11 12 13 14
# 21 22 23 24
# 31 32 33 34

for row in range(1, 4):
  for col in range(1, 5):
    print((row*10)+col, end = " ")
  print()

# 1 1 1 1
# 0 0 0 0
# 1 1 1 1
# 0 0 0 0


for row in range(1, 5):
  for col in range(1, 5):

    if row % 2 == 0:
      print("1 ", end = " ")
    else:
      print("0 ", end = " ")
  print()

for row in range(1, 5):
  for col in range(1, 5):
    print(row%2, end = " ")
  print()

# 1 0 1 0
# 1 0 1 0
# 1 0 1 0
# 1 0 1 0

for row in range(1, 5):
  for col in range(1, 5):
    print(col%2, end = " ")
  print()

# 1
# 1 0
# 1 0 1
# 1 0 1 0

for row in range(1, 5):
  for col in range(1, row+1):
    print(col%2 , end = " ")
  print()

# Collection Data Types

1. list
2. tuple
3. dict
4. set

# 1. list

-> we can store hetrogeneous
-> indexing concept is applicable
-> inserting order is preserve
-> we can store duplicates
-> we can use slice
-> growanle in nature
-> mutable

list = []

type(list)

id(list)

-> append(para)
-> insert(index, value)
-> min()
-> max()
> sort()
-> sorted()
-> pop()

l = [10, 10, 20, 30, True, 10 + 0j,  "Dhanraj", 10.9]
l

for values in l:
  print(values)

for index in range(len(l)):
  print("at ", index , " we have ", l[index])

l = [10, 20, 30]
id(l)

l.append(500)
l

id(l)

l.insert(1, 1)

l

l.pop()
l

sum(l)
print(min(l), max(l), sum(l))

# define a empty list and i
# insert elements till first blank is given
# print --> list, min, max, avg

user_order_list = []

while True:

  user_order = input("Add To Cart -> ")

  if user_order == "":
    break
  else:
    user_order_list.append(int(user_order))

print(user_order_list)
print("Max -> ", max(user_order_list),  " Min : ", min(user_order_list),  "Avg : ", sum(user_order_list)/ len(user_order_list))

'''
define list

Sample Input --> 10, 20, 30, 40, 50, 1, 10, 20

find avg and display

like avg = 30

if avg > element ---> num += 10 otherwise num -= 5

'''

l = [10, 20, 30, 40, 50, 1, 10, 20]

avg = sum(l) // len(l)
for element in range(len(l)):

  if l[element] > avg:
    l[element] -= 5
  else:
    l[element] += 10

print("Avg is : ", avg)
print("Final list -> ", l)

l = [10, 20,10, 10, 20]
l.count(10)

# # without using count function solve the question

# Sample input --> l = [10, 20,10, 10, 20]
# Expected output --> 3


l = [10, 20,10, 10, 20]
count = 0
element = 10

for x in l:
  if x == element:
    count += 1

print("Count is : ", count)

list1 = [10, 20, 30, 40, 55]
list2 = [1, 2, 3, 4]

for x in range(len(list2)):
  list1[x] += list2[x]

print(list1)

# define a list
# if element is odd then add
# if element is even the multiply
# print list, odd , even, and addition of odd + even


l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even = 1
odd = 0

for element in l:
  if element % 2 == 0:
    even *= element
  else:
    odd += element

print("Odd numbers addition is : ", odd)
print("Odd numbers addition is : ", even)
print("Odd numbers addition is : ", even + odd)

l = [1, 2, 3, 4, 5]

for x in range(len(l)):
  out = l.pop()
  l.insert(0, out)
  print(l)

print("------------------------")

for x in range(len(l)):
  out = l.pop(0)
  l.append(out)
  print(l)

# set

'''
-> set() , {at least one element}
-> hetrogeneous
-> duplicates not allow
-> order not preserved
-> indexing not applicable
-> growable in nature
'''

s = {}
type(s)

s = set()
type(s)

s = {1}
type(s)

s = {1, 1, 1, 1, 1, 1, 1}
s

s = {1, 2, 3, 4, 5}
s.pop()
s

l = [1, 2, 3, 4]
l.remove(1)
l

l = [1, 2, 3, 4]
l.remove(10)
l

l = {1, 2, 3, 4}
l.remove(1)
l

l = {1, 2, 3, 4}
l.remove(10)
l

s = {1, 2, 3, 4}
s.discard(10)
s

s = {1}
id(s)

s.add(3)

id(s)

l = [1, 3, 0, -1, 1]

l.sort()   # within sort

print(l.sort())

l = [1, 3, 0, -1, 1, 0]
print(sorted(l))

# Sample Input --> l = [1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 0, 9, 1]
# Expected output -->

# 1 -> 4
# 2 -> 3
# 3 -> 4
# 0 -> 1
# 9 -> 1


l = [1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 0, 9, 1]

unique_list = set(l)

for x in unique_list:
  print(x , " -> ", l.count(x))

# Tuple

-> htro
-> ()
-> Immutable

t = ()
type(t)

id(t)

t = (1, 2)
id(t)

t = ([1],)
id(t)

t[0].append(10)
t

id(t)

# dict

# key : value

d = {1 : "Python", 1 : "Java"}
d

d = {1 : "Python", 1 : "Java"}
d.items()

d = {1 : "Python", 2 : "Java", 3 : "Ruby", 4 : "R"}

for key, value in d.items():
  print("key : ", key ,  " Value : ", value)

d.values()

d.keys()

# Sample Input --> l = [1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 0, 9, 1]
# Expected output -->

# { 1 : 4
# 2 : 3
# 3 : 4
# 0 : 1
# 9 : 1
# }

l = [1, 2, 3, 1, 2, 3, 3, 3, 2, 1, 0, 9, 1]

unique_list = sorted(set(l))
my_dict = {}

for x in unique_list:
  my_dict[x] = l.count(x)

print(my_dict)

# Project

# You are a tea stall owner
# selling products --> tea = 12, coffee = 30, water = 20, banmaska =100
# print total amount




tea = coffee = banmaska = water = 0
while True:

  waiter = input("Do You Want To Order : (Y/N)")

  if waiter == "Y":

    user_order = int(input("1. Tea \t\t 12 \n2. Coffee \t 30 \n3. Water \t 20 \n4. Ban Maska \t 100 \n0. Exit \n"))

    if user_order == 1:
      print("Tea Selected...")
      tea += 1

    elif user_order == 2:
      print(" Coffee Selected...")
      coffee += 1

    elif user_order == 3:
      print(" Water Selected...")
      water += 1

    elif user_order == 4:
      print("BunMaska Selected...")
      banmaska += 1

    elif user_order == 0:
      print("Thanks For Ordering...")
      break

    else:
      print("Bhai dekh ke...")

  elif waiter == "N":
    pass



total_amount = (tea*12) + (coffee*30) + (water * 20) + (banmaska*100)
print("Total Payable amount is : " ,  total_amount)

Bill No : 1000000101
-----------------------------
Tea     12    2   24
Coffee  30    2   60
----------------------------
Total Amount :    84

import time

bill_no = 1000000100
tea = coffee = water = banmaska = 0

while True:

  machine = input("Machine On or OFF : (Y/N) ? ")

  if machine == "Y":

    yes_no = input("Any Order : (Y/N) ? ")

    if yes_no == "Y":

      tea = int(input("Tea : "))
      coffee = int(input("Coffee : "))
      banmaska = int(input("Banmaska : "))
      water = int(input("Water  : "))


      # printing bill

      bill_no += 1

      for x in range(10):
        time.sleep(1)
        print("---", end = "")

      print("\nBill No : ", bill_no)
      print("----------------------------------")

      if tea > 0:
        print("Tea  \t\t  12 ", tea, (tea*12))

      if coffee > 0:
        print("Coffee  \t\t  12 ", coffee, (coffee*30))

      if water > 0:
        print("water  \t\t  12 ", water, (water*20))

      if banmaska > 0:
        print("BanMaska  \t  12 ", banmaska, (banmaska*100))

      print("----------------------------------")

      print("Total Payable Amount : " , (tea*12) + (coffee*30) + (water * 20) + (banmaska*100))

      print("      Visit Again\n\n")


    elif yes_no == "N":
      print("Ok...")

  elif machine == "N":
    print("Switch Off...")
    break


  else:
    print("Please Provide Correct Input ")

