# -*- coding: utf-8 -*-
"""Day-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6Ilbb4lkit78OsvrH0RcsUnKwXtqk0I
"""

print('Hello')
print("Hello")
print(''' Hello ''')
print(""" Hello """)

''' Hello, Python is good programming language '''

# hello, Dhanraj

print(__doc__)

# "Hello", 'Dhanraj', How are you ?

print(''' "Hello", 'Dhanraj', How are you ? ''')

print(""" "Hello", 'Dhanraj', How are you ? """ )

name = "Dhanraj"
print(name)

num = 10
print(num)

num = 10
id(num)  # address

num = 10
type(num)   # <class 'int'>

# fundamental data types

# int , bool, complex , float

num = 10
boolean =True
complex_num = 10 + 0j
float_value = 10.0

print(num, " --> ", type(num),  " --> " , id(num))
print(boolean, " --> ", type(boolean), " --> " , id(boolean))
print(complex_num, " --> ", type(complex_num),  " --> " , id(complex_num))
print(float_value, " --> ", type(float_value),  " --> " , id(float_value))

num = 10
print(id(num), num)
num = 20
print(id(num), num)
print(num, id(num))

num = 10
num2 = 5 + 5
num3 = 20 - 10
num4 = 2 * 5

print(id(num))
print(id(num2))
print(id(num3))
print(id(num4))

num1 , num2 = 10, 20
print(num1, num2)

num1 = num2 = num3 = 10
print(num1, num2, num3)

# swap two numbers

num1 = 10
num2 = 20
print("Before : ")
print("num1 : ", num1 , " num2 : ", num2 )
num1 ,  num2 = num2 , num1
print("num1 : ", num1 , " num2 : ", num2 )

# operators

selling_price = 1000
discount = 20
amount = (selling_price * discount ) / 100

print("Price : ", selling_price)
print("Discount : ", discount)
print("-------------------")
print("Payable amount : " , selling_price - amount)

# Area of circle
# process = pi * r^2
# output  -> Area of circle is : area

radius = 10
area = 3.14 * radius * radius
print("Area of circle is : ", area)

# // , **
print(10 / 3)
print(10 // 3)

print(10 ** 2)

# Area of circle
# process = pi * r^2
# output  -> Area of circle is : area

radius = 10
area = 3.14 * radius ** 2

print("Area of circle is : ", area)

# // --> remove last digit
# % ---> display last digit

print(12345 % 10)
print(12345 // 10)

number = 12345
print("Addition of digits is : ",(( number % 10) + ( number % 100) +  (number % 1000) + ( number % 10000)) )

a = 12345
a1 = a % 10
a //= 10
a2 = a % 10
a //= 10
a3 = a % 10
a //= 10
a4 = a % 10
a //= 10
a5 = a % 10
print(a1 + a2 + a3 + a4 + a5)

# logical operator
# and --> when all is needed
# or  --> when any one is needed

print(10 and 10)

print(10 and 20)

if 10 == 10 and 20 == 20:
  pass

# is, is not
num1 = 10
num2 = 20
print(num1 is num2)

# is, is not

num1 = 10
num2 = 10
print(num1 is not num2)

# membership
# in , not in

print("h" in "hello")

# membership
# in , not in

print("h" not in "hello")

input = input("prompt/message")
print(input)

input = input("prompt/message")
print(input, type(input))

# input --> by defalult --> string

# int(), bool(), str(), float()

user_input = bool(input("I want false output : "))
print(user_input)

num1 = input("Enter number : ")
num2 = input("Enter number : ")

print("Addition is : ", num1 + num2)

num1 = int( input("Enter number : "))
num2 = int(input("Enter number : "))

print("Addition is : ", num1 + num2)

user_input = bool(input("I want false output : "))
print(user_input)

# take a input from user
# Sample input --> total_marks = 500
# Expected output --> Your Percentage is : 100.0

# process --> total_marks * 100 / 500

total_marks = int(input("Enter total marks : "))
percentage = total_marks * 100 / 500
print("Your Percentage is : ", percentage)

print("Your Percentage is : ", int(input("Enter total marks : ")) * 100 / 500)

# Take input from user
# Sample input --> f = 100.0
# Expected output --> C = 37.

# process --> (f - 32) * 5/9

print("C : ", (int(input("Enter total marks : ")) - 32) * 5/9)

# take input from user
# Sample input --> 10, 20, 30
# Expected output --> Avg = 20
# process--> num1 + num2 + num3 / total_numbers

# process --> total_marks * 100 / 500

num1 = int(input("Enter total marks : "))
num2 = int(input("Enter total marks : "))
num3 = int(input("Enter total marks : "))

print("Avg is : ", (num1 + num2 + num3 )// 3)

"""**Branching**"""

# Syntax

if condition (Boolean):
  # code // pass

clock = int(input("Enter time : "))

if clock == 10:
  print("Temple")

if clock == 3:
  print("Movie")

if clock == 6:
  print("Party")

user_input= int(input("Enter number : "))

if user_input > 0:
  print(user_input, " +ve")

if user_input < 0:
  print(user_input, " -ve")

clock = int(input("Enter time : "))

if clock == 10:
  print("Temple")

if clock == 3:
  print("Movie")

if clock == 6:
  print("Party")

else:   # if any condition fail
  print("Stay Home Stay Safe")

num = int(input("Enter number "))

if num > 0:
  print(num,  " is positive ")
else:
  print(num," is negative")

if condition:
  # code
elif condition:
  # code
else:
  # code

num = int(input("Enter number "))

if num > 0:
  print(num,  " is positive ")

elif num == 0:
  print("Number is 0")
else:
  print(num," is negative")

# read a  number from user to check number is even or odd
# Sample Input --> 10
# expected output --> 10 is even

# Sample Input --> 15
# expected output --> 10 is odd

# process --> num % 2 == 0 --> if true --> even otherwise --> false

num = int(input())

if num % 2 == 0:
  print(num, " is even")
else:
  print(num, " is odd")

# Read a number from user and check number is accepted or not

# Sample Input --> 15
# expected output --> 15 is accepted

# Sample Input --> 10
# expected output --> 10 is rejected

# process --> if number is perfectly divisible by 3 and 5 then number is accepted otherwise
# number is rejected

# and --> when all is needed
# or --> when any one is needed

num = int(input())
if num % 3 == 0 and num % 5 == 0:
  print(num, " is accepted.")
else:
  print(num, " is rejected")

# Read a number from user and check year is a leap year or not

# Sample Input --> 2000
# expected output --> 2000 is a leap year

year = int(input())
if (year % 4 == 0 and year % 100 != 0 ) or year % 400 == 0:
  print(year ,  " is a leap year")
else:
  print(year ,  " is not a leap year")

# Requirement based question

per < 40  --> fali
per >= 40 ---> per class : pass
per >= 60 ---> per class : first class
per >= 80 ---> per class : merite

machine = input("On or OFF : (Y/N) ")

if machine == "Y":

  # marks
  sub1 = int(input("Enter Marks : "))
  sub2 = int(input("Enter Marks : "))
  sub3 = int(input("Enter Marks : "))

  if sub1 >= 40 and sub2 >= 40 and sub3 >= 40:

    # calculate per
    percentage = ((sub1+sub2+sub3)*100) / 300

    if percentage >= 0 and percentage <= 100:

      if percentage >= 40 and percentage < 60:
        print("Percentage : ", percentage , " Class : Pass")

      elif percentage >= 60 and percentage < 80:
        print("Percentage : ", percentage , " Class : First Class")

      elif percentage >= 80 and percentage <= 100:
        print("Percentage : ", percentage , " Class : Merit")

    else:
      print("Tum se naa ho payee...")

  else:
    print("Try again...")

elif machine == "N":
  print("Turn Off...")

"""**Looping**"""

# for loop
# while loop

while condition:
  pass

# 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

start = 1
# starting --> included, ending --> exluded

while start < 10+1 :  # start <= 10  //  start < 11
  print(start)
  start = start + 1

# 10, ......0

start = 10
while start >= 0:
  print(start)
  start -= 1

# count the digits
# Sample input --> 12345
# Expected output --> count : 5

import time

num = int(input())
count = 0
while num != 0:
  time.sleep(4)
  print(num, "count -> ", count )
  count += 1
  num //= 10

print("Final answer is : ", count)

# count the digits
# Sample input --> 12345
# Expected output --> addition : 15

num = 12234
sum = 0
while num > 0:
  sum += num % 10
  num //= 10
  print("sum --> ", sum)

print("final answer is : ", sum)

# reverse a number
# Sample input --> 12345
# Expected output --> rev : 54321

num = 12234
rev = 0
while num > 0:
  rev = rev * 10 + num % 10
  num //= 10
  print("sum --> ", rev)

print("final answer is : ", rev)

# Read number from user to check number is palindrome or not
# Sample -> 12321
# expected --> 12321 is palindrome

# Sample -> 123211
# expected --> 112321 is not palindrome

num = 1223221
original_num = num
rev = 0
while num > 0:
  rev = rev * 10 + num % 10
  num //= 10

if original_num == rev:
  print(original_num, " is palindrome")
else:
  print(original_num, "is not palindrome")

# for loop

for <var> in collection_dataType:
  print()

a = range(10)
print(type(a))

a

range(starting/initialization, condition, increment/decrement/step)

starting --> optional --> by default --> 0
condition --> mandatory
step --> by default --> +1 --> optional

a = range(1, 10, 1)

a

for x in range(10):
  print(x)

for x in range(1, 10+1):
  print(x)

for x in range(10):
  print("at " , x, " we have : ", x+1)

