# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhKTnzB2pAX9nuPF9ajsdqqaQ5loqA45
"""

import numpy as np
import pandas as pd
import pickle
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import os
import warnings
warnings.simplefilter('ignore')

df = pd.read_csv('dataset_malwares.csv')

df.head(12)

df.info()

# prompt: remove row like name ,ImageDirectoryEntrySecurity ,SectionMainChar

dropped_df = df.drop(['Name', 'ImageDirectoryEntrySecurity', 'SectionMainChar', 'Malware'], axis=1)

ax=sns.countplot(df['Malware'])
ax.set_xticklabels(['Not Malware', 'Malware'])

dropped_df = df.drop(['Name', 'Machine', 'TimeDateStamp', 'Malware'], axis=1)

ax=sns.countplot(df['Malware'])
ax.set_xticklabels(['Not Malware', 'Malware'])

import tensorflow as tf